# Generated by Django 4.2.11 on 2024-05-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=42, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_data', models.TextField()),
            ],
        ),
    ]
