# Generated by Django 4.2.11 on 2024-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='user_data',
        ),
        migrations.AddField(
            model_name='identity',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=46, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
