# Generated by Django 5.0.6 on 2024-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='ethereum_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
