# Generated by Django 5.0.6 on 2024-05-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0003_alter_wallet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
