# Generated by Django 5.0.6 on 2024-05-19 11:27

import django.db.models.deletion
import django.utils.timezone
import sharing.fileManagement
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('fileSize', models.FloatField()),
                ('fileType', models.CharField(max_length=10, null=True)),
                ('fileDir', models.FileField(null=True, upload_to=sharing.fileManagement.user_directory_path)),
                ('fileHash', models.CharField(max_length=64)),
                ('shared', models.BooleanField(default=False)),
                ('created_shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedFiles', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharedFiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_text', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('private_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.privatekey')),
            ],
        ),
        migrations.CreateModel(
            name='ShareData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('time_limit', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_texts_owned', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_texts_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(('fileSize__gte', 0.0)), name='file_size_non_negative_check'),
        ),
    ]
